export module ActionType {
    //do request
    export const SERVICE_UNIT_CREATE_REQUEST = "CREATE_SERVICE_UNIT_REQUEST";
    export const SERVICE_UNIT_CREATE_SUCCESS = "CREATE_SERVICE_UNIT_SUCCESS";
    export const SERVICE_UNIT_CREATE_ERROR = "CREATE_SERVICE_UNIT_ERROR";

    export const SERVICE_UNIT_EDIT_REQUEST = "EDIT_SERVICE_UNIT_REQUEST";
    export const SERVICE_UNIT_EDIT_SUCCESS = "EDIT_SERVICE_UNIT_SUCCESS";
    export const SERVICE_UNIT_EDIT_ERROR = "EDIT_SERVICE_UNIT_ERROR";

    export const SERVICE_UNIT_DELETE_REQUEST = "DELETE_SERVICE_UNIT_REQUEST";
    export const SERVICE_UNIT_DELETE_SUCCESS = "DELETE_SERVICE_UNIT_SUCCESS";
    export const SERVICE_UNIT_DELETE_ERROR = "DELETE_SERVICE_UNIT_ERROR";

    //get request
    export const GET_UNIQUE_SERVICE_UNIT_REQUEST = "GET_UNIQUE_SERVICE_UNIT_REQUEST";
    export const GET_UNIQUE_SERVICE_UNIT_SUCCESS = "GET_UNIQUE_SERVICE_UNIT_SUCCESS";
    export const GET_UNIQUE_SERVICE_UNIT_ERROR = "GET_UNIQUE_SERVICE_UNIT_ERROR";

    export const GET_SERVICE_UNITS_REQUEST = "GET_SERVICE_UNITS_REQUEST";
    export const GET_SERVICE_UNITS_SUCCESS = "GET_SERVICE_UNITS_SUCCESS";
    export const GET_SERVICE_UNITS_ERROR = "GET_SERVICE_UNITS_ERROR";

    export const LIST_SERVICE_UNITS_WITH_PAGING_REQUEST = "LIST_SERVICE_UNITS_WITH_PAGING_REQUEST";
    export const LIST_SERVICE_UNITS_WITH_PAGING_SUCCESS = "LIST_SERVICE_UNITS_WITH_PAGING_SUCCESS";
    export const LIST_SERVICE_UNITS_WITH_PAGING_ERROR = "LIST_SERVICE_UNITS_WITH_PAGING_ERROR"
}
