export module ActionType {
    export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
    export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
    export const BRANCH_CREATE_ERROR = "BRANCH_CREATE_ERROR";

    export const BRANCH_EDIT_REQUEST = "BRANCH_EDIT_REQUEST";
    export const BRANCH_EDIT_SUCCESS = "BRANCH_EDIT_SUCCESS";
    export const BRANCH_EDIT_ERROR = "BRANCH_EDIT_ERROR";

    export const BRANCH_DELETE_REQUEST = "BRANCH_DELETE_REQUEST";
    export const BRANCH_DELETE_SUCCESS = "BRANCH_DELETE_SUCCESS";
    export const BRANCH_DELETE_ERROR = "BRANCH_DELETE_ERROR";

    export const GET_UNIQUE_BRANCH_REQUEST = "GET_UNIQUE_BRANCH_REQUEST";
    export const GET_UNIQUE_BRANCH_SUCCESS = "GET_UNIQUE_BRANCH_SUCCESS";
    export const GET_UNIQUE_BRANCH_ERROR = "GET_UNIQUE_BRANCH_ERROR";

    export const GET_BRANCHES_REQUEST = "GET_BRANCHES_REQUEST";
    export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
    export const GET_BRANCHES_ERROR = "GET_BRANCHES_ERROR";

    export const LIST_BRANCHES_WITH_PAGING_REQUEST = "LIST_BRANCHES_WITH_PAGING_REQUEST";
    export const LIST_BRANCHES_WITH_PAGING_SUCCESS = "LIST_BRANCHES_WITH_PAGING_SUCCESS";
    export const LIST_BRANCHES_WITH_PAGING_ERROR = "LIST_BRANCHES_WITH_PAGING_ERROR";
}
