export module ActionType {
    //do request
    export const CUSTOMER_CREATE_REQUEST = "CREATE_CUSTOMER_REQUEST";
    export const CUSTOMER_CREATE_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
    export const CUSTOMER_CREATE_ERROR = "CREATE_CUSTOMER_ERROR";

    export const CUSTOMER_EDIT_REQUEST = "EDIT_CUSTOMER_REQUEST";
    export const CUSTOMER_EDIT_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
    export const CUSTOMER_EDIT_ERROR = "EDIT_CUSTOMER_ERROR";

    export const CUSTOMER_DELETE_REQUEST = "DELETE_CUSTOMER_REQUEST";
    export const CUSTOMER_DELETE_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
    export const CUSTOMER_DELETE_ERROR = "DELETE_CUSTOMER_ERROR";

    //get request
    export const GET_UNIQUE_CUSTOMER_REQUEST = "GET_UNIQUE_CUSTOMER_REQUEST";
    export const GET_UNIQUE_CUSTOMER_SUCCESS = "GET_UNIQUE_CUSTOMER_SUCCESS";
    export const GET_UNIQUE_CUSTOMER_ERROR = "GET_UNIQUE_CUSTOMER_ERROR";

    export const GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST";
    export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
    export const GET_CUSTOMERS_ERROR = "GET_CUSTOMERS_ERROR";

    export const LIST_CUSTOMERS_WITH_PAGING_REQUEST = "LIST_CUSTOMERS_WITH_PAGING_REQUEST";
    export const LIST_CUSTOMERS_WITH_PAGING_SUCCESS = "LIST_CUSTOMERS_WITH_PAGING_SUCCESS";
    export const LIST_CUSTOMERS_WITH_PAGING_ERROR = "LIST_CUSTOMERS_WITH_PAGING_ERROR";
}
