export const ActionType = {
    GET_PERMISSION_BY_USER_REQUEST: "GET_PERMISSION_BY_USER_REQUEST",
    GET_PERMISSION_BY_USER_SUCCESS: "GET_PERMISSION_BY_USER_SUCCESS",
    GET_PERMISSION_BY_USER_ERROR: "GET_PERMISSION_BY_USER_ERROR",

    GET_PERMISSION_BY_ROLE_REQUEST: "GET_PERMISSION_BY_ROLE_REQUEST",
    GET_PERMISSION_BY_ROLE_SUCCESS: "GET_PERMISSION_BY_ROLE_SUCCESS",
    GET_PERMISSION_BY_ROLE_ERROR: "GET_PERMISSION_BY_ROLE_ERROR",

    GET_ROLE_REQUEST: "GET_ROLE_REQUEST",
    GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
    GET_ROLE_ERROR: "GET_ROLE_ERROR",

    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_ERROR: "GET_USER_ERROR",

    GET_MODULE_REQUEST: "GET_MODULE_REQUEST",
    GET_MODULE_SUCCESS: "GET_MODULE_SUCCESS",
    GET_MODULE_ERROR: "GET_MODULE_ERROR",

    SAVE_PERMISSION_REQUEST: "SAVE_PERMISSION_REQUEST",
    SAVE_PERMISSION_SUCCESS: "SAVE_PERMISSION_SUCCESS",
    SAVE_PERMISSION_ERROR: "SAVE_PERMISSION_ERROR"
}