export module ActionType {
    //do request
    export const MANUFACTURER_CREATE_REQUEST = "CREATE_MANUFACTURER_REQUEST";
    export const MANUFACTURER_CREATE_SUCCESS = "CREATE_MANUFACTURER_SUCCESS";
    export const MANUFACTURER_CREATE_ERROR = "CREATE_MANUFACTURER_ERROR";

    export const MANUFACTURER_EDIT_REQUEST = "EDIT_MANUFACTURER_REQUEST";
    export const MANUFACTURER_EDIT_SUCCESS = "EDIT_MANUFACTURER_SUCCESS";
    export const MANUFACTURER_EDIT_ERROR = "EDIT_MANUFACTURER_ERROR";

    export const MANUFACTURER_DELETE_REQUEST = "DELETE_MANUFACTURER_REQUEST";
    export const MANUFACTURER_DELETE_SUCCESS = "DELETE_MANUFACTURER_SUCCESS";
    export const MANUFACTURER_DELETE_ERROR = "DELETE_MANUFACTURER_ERROR";

    //get request
    export const GET_UNIQUE_MANUFACTURER_REQUEST = "GET_UNIQUE_MANUFACTURER_REQUEST";
    export const GET_UNIQUE_MANUFACTURER_SUCCESS = "GET_UNIQUE_MANUFACTURER_SUCCESS";
    export const GET_UNIQUE_MANUFACTURER_ERROR = "GET_UNIQUE_MANUFACTURER_ERROR";

    export const GET_MANUFACTURERS_REQUEST = "GET_MANUFACTURERS_REQUEST";
    export const GET_MANUFACTURERS_SUCCESS = "GET_MANUFACTURERS_SUCCESS";
    export const GET_MANUFACTURERS_ERROR = "GET_MANUFACTURERS_ERROR";

    export const GET_ALL_MANUFACTURERS_REQUEST = "GET_ALL_MANUFACTURERS_REQUEST";
    export const GET_ALL_MANUFACTURERS_SUCCESS = "GET_ALL_MANUFACTURERS_SUCCESS";
    export const GET_ALL_MANUFACTURERS_ERROR = "GET_ALL_MANUFACTURERS_ERROR";

    export const LIST_MANUFACTURERS_WITH_PAGING_REQUEST = "LIST_MANUFACTURERS_WITH_PAGING_REQUEST";
    export const LIST_MANUFACTURERS_WITH_PAGING_SUCCESS = "LIST_MANUFACTURERS_WITH_PAGING_SUCCESS";
    export const LIST_MANUFACTURERS_WITH_PAGING_ERROR = "LIST_MANUFACTURERS_WITH_PAGING_ERROR"
}
