export module ActionType {
    //do request
    export const EMPLOYEE_CREATE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
    export const EMPLOYEE_CREATE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
    export const EMPLOYEE_CREATE_ERROR = "CREATE_EMPLOYEE_ERROR";

    export const EMPLOYEE_EDIT_REQUEST = "EDIT_EMPLOYEE_REQUEST";
    export const EMPLOYEE_EDIT_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
    export const EMPLOYEE_EDIT_ERROR = "EDIT_EMPLOYEE_ERROR";

    export const EMPLOYEE_DELETE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
    export const EMPLOYEE_DELETE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
    export const EMPLOYEE_DELETE_ERROR = "DELETE_EMPLOYEE_ERROR";

    //get request
    export const GET_UNIQUE_EMPLOYEE_REQUEST = "GET_UNIQUE_EMPLOYEE_REQUEST";
    export const GET_UNIQUE_EMPLOYEE_SUCCESS = "GET_UNIQUE_EMPLOYEE_SUCCESS";
    export const GET_UNIQUE_EMPLOYEE_ERROR = "GET_UNIQUE_EMPLOYEE_ERROR";

    export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
    export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
    export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR";

    export const GET_ALL_EMPLOYEES_REQUEST = "GET_ALL_EMPLOYEES_REQUEST";
    export const GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS";
    export const GET_ALL_EMPLOYEES_ERROR = "GET_ALL_EMPLOYEES_ERROR";

    export const LIST_EMPLOYEES_WITH_PAGING_REQUEST = "LIST_EMPLOYEES_WITH_PAGING_REQUEST";
    export const LIST_EMPLOYEES_WITH_PAGING_SUCCESS = "LIST_EMPLOYEES_WITH_PAGING_SUCCESS";
    export const LIST_EMPLOYEES_WITH_PAGING_ERROR = "LIST_EMPLOYEES_WITH_PAGING_ERROR";
};
