export module ActionType {
    export const ACCESSARY_CREATE_REQUEST = "ACCESSARY_CREATE_REQUEST";
    export const ACCESSARY_CREATE_SUCCESS = "ACCESSARY_CREATE_SUCCESS";
    export const ACCESSARY_CREATE_ERROR = "ACCESSARY_CREATE_ERROR";

    export const ACCESSARY_EDIT_REQUEST = "ACCESSARY_EDIT_REQUEST";
    export const ACCESSARY_EDIT_SUCCESS = "ACCESSARY_EDIT_SUCCESS";
    export const ACCESSARY_EDIT_ERROR = "ACCESSARY_EDIT_ERROR";

    export const ACCESSARY_DELETE_REQUEST = "ACCESSARY_DELETE_REQUEST";
    export const ACCESSARY_DELETE_SUCCESS = "ACCESSARY_DELETE_SUCCESS";
    export const ACCESSARY_DELETE_ERROR = "ACCESSARY_DELETE_ERROR";
    
    export const GET_UNIQUE_ACCESSARY_REQUEST = "GET_UNIQUE_ACCESSARY_REQUEST";
    export const GET_UNIQUE_ACCESSARY_SUCCESS = "GET_UNIQUE_ACCESSARY_SUCCESS";
    export const GET_UNIQUE_ACCESSARY_ERROR = "GET_UNIQUE_ACCESSARY_ERROR";

    export const GET_ALL_ACCESSARIES_REQUEST = "GET_ALL_ACCESSARIES_REQUEST";
    export const GET_ALL_ACCESSARIES_SUCCESS = "GET_ALL_ACCESSARIES_SUCCESS";
    export const GET_ALL_ACCESSARIES_ERROR = "GET_ALL_ACCESSARIES_ERROR";

    export const LIST_ACCESSARIES_WITH_PAGING_REQUEST = "LIST_ACCESSARIES_WITH_PAGING_REQUEST";
    export const LIST_ACCESSARIES_WITH_PAGING_SUCCESS = "LIST_ACCESSARIES_WITH_PAGING_SUCCESS";
    export const LIST_ACCESSARIES_WITH_PAGING_ERROR = "LIST_ACCESSARIES_WITH_PAGING_ERROR";
}
