export module ActionType {
    //do request
    export const YEAR_CREATE_REQUEST = "CREATE_YEAR_REQUEST";
    export const YEAR_CREATE_SUCCESS = "CREATE_YEAR_SUCCESS";
    export const YEAR_CREATE_ERROR = "CREATE_YEAR_ERROR";

    export const YEAR_EDIT_REQUEST = "EDIT_YEAR_REQUEST";
    export const YEAR_EDIT_SUCCESS = "EDIT_YEAR_SUCCESS";
    export const YEAR_EDIT_ERROR = "EDIT_YEAR_ERROR";

    export const YEAR_DELETE_REQUEST = "DELETE_YEAR_REQUEST";
    export const YEAR_DELETE_SUCCESS = "DELETE_YEAR_SUCCESS";
    export const YEAR_DELETE_ERROR = "DELETE_YEAR_ERROR";

    //get request
    export const GET_UNIQUE_YEAR_REQUEST = "GET_UNIQUE_YEAR_REQUEST";
    export const GET_UNIQUE_YEAR_SUCCESS = "GET_UNIQUE_YEAR_SUCCESS";
    export const GET_UNIQUE_YEAR_ERROR = "GET_UNIQUE_YEAR_ERROR";

    export const GET_YEARS_REQUEST = "GET_YEARS_REQUEST";
    export const GET_YEARS_SUCCESS = "GET_YEARS_SUCCESS";
    export const GET_YEARS_ERROR = "GET_YEARS_ERROR";

    export const GET_ALL_YEARS_REQUEST = "GET_ALL_YEARS_REQUEST";
    export const GET_ALL_YEARS_SUCCESS = "GET_ALL_YEARS_SUCCESS";
    export const GET_ALL_YEARS_ERROR = "GET_ALL_YEARS_ERROR";

    export const LIST_YEARS_WITH_PAGING_REQUEST = "LIST_YEARS_WITH_PAGING_REQUEST";
    export const LIST_YEARS_WITH_PAGING_SUCCESS = "LIST_YEARS_WITH_PAGING_SUCCESS";
    export const LIST_YEARS_WITH_PAGING_ERROR = "LIST_YEARS_WITH_PAGING_ERROR";
}
