export const ActionType = {
    //do request
    GET_PRINT_TEMPLATE_REQUEST: "GET_PRINT_TEMPLATE_REQUEST",
    GET_PRINT_TEMPLATE_SUCCESS: "GET_PRINT_TEMPLATE_SUCCESS",
    GET_PRINT_TEMPLATE_ERROR: "GET_PRINT_TEMPLATE_ERROR",

    ADD_OR_UPDATE_PRINT_TEMPLATE_REQUEST: "ADD_OR_UPDATE_PRINT_TEMPLATE_REQUEST",
    ADD_OR_UPDATE_PRINT_TEMPLATE_SUCCESS: "ADD_OR_UPDATE_PRINT_TEMPLATE_SUCCESS",
    ADD_OR_UPDATE_PRINT_TEMPLATE_ERROR: "ADD_OR_UPDATE_PRINT_TEMPLATE_ERROR"
};
