export module ActionType {
    //do request
    export const QUOTATION_CREATE_REQUEST = "CREATE_QUOTATION_REQUEST";
    export const QUOTATION_CREATE_SUCCESS = "CREATE_QUOTATION_SUCCESS";
    export const QUOTATION_CREATE_ERROR = "CREATE_QUOTATION_ERROR";

    export const QUOTATION_UPDATE_REQUEST = "QUOTATION_UPDATE_REQUEST";
    export const QUOTATION_UPDATE_SUCCESS = "QUOTATION_UPDATE_SUCCESS";
    export const QUOTATION_UPDATE_ERROR = "QUOTATION_UPDATE_ERROR";

    export const QUOTATION_UPDATE_ONLY_QUOTATION_INFO_REQUEST = "QUOTATION_UPDATE_ONLY_QUOTATION_INFO_REQUEST";
    export const QUOTATION_UPDATE_ONLY_QUOTATION_INFO_SUCCESS = "QUOTATION_UPDATE_ONLY_QUOTATION_INFO_SUCCESS";
    export const QUOTATION_UPDATE_ONLY_QUOTATION_INFO_ERROR = "QUOTATION_UPDATE_ONLY_QUOTATION_INFO_ERROR";

    export const QUOTATION_CHANGE_STATUS_REQUEST = "QUOTATION_CHANGE_STATUS_REQUEST";
    export const QUOTATION_CHANGE_STATUS_SUCCESS = "QUOTATION_CHANGE_STATUS_SUCCESS";
    export const QUOTATION_CHANGE_STATUS_ERROR = "QUOTATION_CHANGE_STATUS_ERROR";

    export const QUOTATION_ITEM_CREATE_REQUEST = "QUOTATION_ITEM_CREATE_REQUEST";
    export const QUOTATION_ITEM_CREATE_SUCCESS = "QUOTATION_ITEM_CREATE_SUCCESS";
    export const QUOTATION_ITEM_CREATE_ERROR = "QUOTATION_ITEM_CREATE_ERROR";

    export const QUOTATION_ITEM_EDIT_REQUEST = "QUOTATION_ITEM_EDIT_REQUEST";
    export const QUOTATION_ITEM_EDIT_SUCCESS = "QUOTATION_ITEM_EDIT_SUCCESS";
    export const QUOTATION_ITEM_EDIT_ERROR = "QUOTATION_ITEM_EDIT_ERROR";

    export const QUOTATION_ITEM_DELETE_REQUEST = "QUOTATION_ITEM_DELETE_REQUEST";
    export const QUOTATION_ITEM_DELETE_SUCCESS = "QUOTATION_ITEM_DELETE_SUCCESS";
    export const QUOTATION_ITEM_DELETE_ERROR = "QUOTATION_ITEM_DELETE_ERROR";

    export const QUOTATION_MULTIPLE_ITEM_CREATE_REQUEST = "QUOTATION_MULTIPLE_ITEM_CREATE_REQUEST";
    export const QUOTATION_MULTIPLE_ITEM_CREATE_SUCCESS = "QUOTATION_MULTIPLE_ITEM_CREATE_SUCCESS";
    export const QUOTATION_MULTIPLE_ITEM_CREATE_ERROR = "QUOTATION_MULTIPLE_ITEM_CREATE_ERROR";

    export const QUOTATION_UPDATE_EMPLOYEES_REQUEST = "QUOTATION_UPDATE_EMPLOYEES_REQUEST";
    export const QUOTATION_UPDATE_EMPLOYEES_SUCCESS = "QUOTATION_UPDATE_EMPLOYEES_SUCCESS";
    export const QUOTATION_UPDATE_EMPLOYEES_ERROR = "QUOTATION_UPDATE_EMPLOYEES_ERROR";

    export const QUOTATION_UPDATE_ITEMS_REQUEST = "QUOTATION_UPDATE_ITEMS_REQUEST";
    export const QUOTATION_UPDATE_ITEMS_SUCCESS = "QUOTATION_UPDATE_ITEMS_SUCCESS";
    export const QUOTATION_UPDATE_ITEMS_ERROR = "QUOTATION_UPDATE_ITEMS_ERROR";

    export const RECEIPTS_CREATE_OR_UPDATE_REQUEST = "RECEIPTS_CREATE_OR_UPDATE_REQUEST";
    export const RECEIPTS_CREATE_OR_UPDATE_SUCCESS = "RECEIPTS_CREATE_OR_UPDATE_SUCCESS";
    export const RECEIPTS_CREATE_OR_UPDATE_ERROR = "RECEIPTS_CREATE_OR_UPDATE_ERROR";

    export const PAYSLIP_CREATE_OR_UPDATE_REQUEST = "PAYSLIP_CREATE_OR_UPDATE_REQUEST";
    export const PAYSLIP_CREATE_OR_UPDATE_SUCCESS = "PAYSLIP_CREATE_OR_UPDATE_SUCCESS";
    export const PAYSLIP_CREATE_OR_UPDATE_ERROR = "PAYSLIP_CREATE_OR_UPDATE_ERROR";

    export const QUOTATION_NOTE_UPDATE_SPECIFY_STEP_REQUEST = "QUOTATION_NOTE_UPDATE_SPECIFY_STEP_REQUEST";
    export const QUOTATION_NOTE_UPDATE_SPECIFY_STEP_SUCCESS = "QUOTATION_NOTE_UPDATE_SPECIFY_STEP_SUCCESS";
    export const QUOTATION_NOTE_UPDATE_SPECIFY_STEP_ERROR = "QUOTATION_NOTE_UPDATE_SPECIFY_STEP_ERROR";
    
    //get request
    export const GET_UNIQUE_QUOTATION_REQUEST = "GET_UNIQUE_QUOTATION_REQUEST";
    export const GET_UNIQUE_QUOTATION_SUCCESS = "GET_UNIQUE_QUOTATION_SUCCESS";
    export const GET_UNIQUE_QUOTATION_ERROR = "GET_UNIQUE_QUOTATION_ERROR";

    export const GET_ALL_SPECIFIED_QUOTATION_INFO_REQUEST = "GET_ALL_SPECIFIED_QUOTATION_INFO_REQUEST";
    export const GET_ALL_SPECIFIED_QUOTATION_INFO_SUCCESS = "GET_ALL_SPECIFIED_QUOTATION_INFO_SUCCESS";
    export const GET_ALL_SPECIFIED_QUOTATION_INFO_ERROR = "GET_ALL_SPECIFIED_QUOTATION_INFO_ERROR";

    export const GET_UNIQUE_QUOTATION_ITEM_REQUEST = "GET_UNIQUE_QUOTATION_ITEM_REQUEST";
    export const GET_UNIQUE_QUOTATION_ITEM_SUCCESS = "GET_UNIQUE_QUOTATION_ITEM_SUCCESS";
    export const GET_UNIQUE_QUOTATION_ITEM_ERROR = "GET_UNIQUE_QUOTATION_ITEM_ERROR";

    export const GET_ALL_QUOTATION_ITEMS_REQUEST = "GET_ALL_QUOTATION_ITEMS_REQUEST";
    export const GET_ALL_QUOTATION_ITEMS_SUCCESS = "GET_ALL_QUOTATION_ITEMS_SUCCESS";
    export const GET_ALL_QUOTATION_ITEMS_ERROR = "GET_ALL_QUOTATION_ITEMS_ERROR";

    export const INITIALIZE_NEW_QUOTATION_ITEM_REQUEST = "INITIALIZE_NEW_QUOTATION_ITEM_REQUEST";
    export const INITIALIZE_NEW_QUOTATION_ITEM_SUCCESS = "INITIALIZE_NEW_QUOTATION_ITEM_SUCCESS";
    export const INITIALIZE_NEW_QUOTATION_ITEM_ERROR = "INITIALIZE_NEW_QUOTATION_ITEM_ERROR";
    
    export const GET_EMPLOYEES_BY_QUOTATION_REQUEST = "GET_EMPLOYEES_BY_QUOTATION_REQUEST";
    export const GET_EMPLOYEES_BY_QUOTATION_SUCCESS = "GET_EMPLOYEES_BY_QUOTATION_SUCCESS";
    export const GET_EMPLOYEES_BY_QUOTATION_ERROR = "GET_EMPLOYEES_BY_QUOTATION_ERROR";
    
    export const GET_UNIQUE_RECEIPT_REQUEST = "GET_UNIQUE_RECEIPT_REQUEST";
    export const GET_UNIQUE_RECEIPT_SUCCESS = "GET_UNIQUE_RECEIPT_SUCCESS";
    export const GET_UNIQUE_RECEIPT_ERROR = "GET_UNIQUE_RECEIPT_ERROR";
    
    export const GET_UNIQUE_PAYSLIP_REQUEST = "GET_UNIQUE_PAYSLIP_REQUEST";
    export const GET_UNIQUE_PAYSLIP_SUCCESS = "GET_UNIQUE_PAYSLIP_SUCCESS";
    export const GET_UNIQUE_PAYSLIP_ERROR = "GET_UNIQUE_PAYSLIP_ERROR";
    
    export const RECEIPTS_PAGING_REQUEST = "RECEIPTS_PAGING_REQUEST";
    export const RECEIPTS_PAGING_SUCCESS = "RECEIPTS_PAGING_SUCCESS";
    export const RECEIPTS_PAGING_ERROR = "RECEIPTS_PAGING_ERROR";
    
    export const PAYSLIP_PAGING_REQUEST = "PAYSLIP_PAGING_REQUEST";
    export const PAYSLIP_PAGING_SUCCESS = "PAYSLIP_PAGING_SUCCESS";
    export const PAYSLIP_PAGING_ERROR = "PAYSLIP_PAGING_SUCCESS";
    
    export const GET_PENDING_QUOTATIONS_REQUEST = "GET_PENDING_QUOTATIONS_REQUEST";
    export const GET_PENDING_QUOTATIONS_SUCCESS = "GET_PENDING_QUOTATIONS_SUCCESS";
    export const GET_PENDING_QUOTATIONS_ERROR = "GET_PENDING_QUOTATIONS_ERROR";
    
    export const GET_ALL_QUOTATIONS_BY_SEARCH_TERM_REQUEST = "GET_ALL_QUOTATIONS_BY_SEARCH_TERM_REQUEST";
    export const GET_ALL_QUOTATIONS_BY_SEARCH_TERM_SUCCESS = "GET_ALL_QUOTATIONS_BY_SEARCH_TERM_SUCCESS";
    export const GET_ALL_QUOTATIONS_BY_SEARCH_TERM_ERROR = "GET_ALL_QUOTATIONS_BY_SEARCH_TERM_ERROR";
    
    export const LIST_ITEMS_BY_QUOTATION_REQUEST = "LIST_ITEMS_BY_QUOTATION_REQUEST";
    export const LIST_ITEMS_BY_QUOTATION_SUCCESS = "LIST_ITEMS_BY_QUOTATION_SUCCESS";
    export const LIST_ITEMS_BY_QUOTATION_ERROR = "LIST_ITEMS_BY_QUOTATION_ERROR";
    
    export const FILTER_CUSTOMER_OWNED_CARS_REQUEST = "ATTACH_CUSTOMER_CAR_TO_QUOTATION_REQUEST";
    export const FILTER_CUSTOMER_OWNED_CARS_SUCCESS = "ATTACH_CUSTOMER_CAR_TO_QUOTATION_SUCCESS";
    export const FILTER_CUSTOMER_OWNED_CARS_ERROR = "ATTACH_CUSTOMER_CAR_TO_QUOTATION_ERROR";
    
    export const CUSTOMER_EXCHANGE_WITH_PAGING_REQUEST = "CUSTOMER_EXCHANGE_WITH_PAGING_REQUEST";
    export const CUSTOMER_EXCHANGE_WITH_PAGING_SUCCESS = "CUSTOMER_EXCHANGE_WITH_PAGING_SUCCESS";
    export const CUSTOMER_EXCHANGE_WITH_PAGING_ERROR = "CUSTOMER_EXCHANGE_WITH_PAGING_ERROR";
    
    export const LIST_QUOTATION_WITH_PAGING_REQUEST = "LIST_QUOTATION_WITH_PAGING_REQUEST";
    export const LIST_QUOTATION_WITH_PAGING_SUCCESS = "LIST_QUOTATION_WITH_PAGING_SUCCESS";
    export const LIST_QUOTATION_WITH_PAGING_ERROR = "LIST_QUOTATION_WITH_PAGING_ERROR";

    export const GET_UNIQUE_QUOTATION_NOTE_REQUEST = "GET_UNIQUE_QUOTATION_NOTE_REQUEST";
    export const GET_UNIQUE_QUOTATION_NOTE_SUCCESS = "GET_UNIQUE_QUOTATION_NOTE_SUCCESS";
    export const GET_UNIQUE_QUOTATION_NOTE_ERROR = "GET_UNIQUE_QUOTATION_NOTE_ERROR";

    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_REQUEST = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_REQUEST";
    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_SUCCESS = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_SUCCESS";
    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_ERROR = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_CATEGORY_ERROR";

    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_REQUEST = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_REQUEST";
    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_SUCCESS = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_SUCCESS";
    export const GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_ERROR = "GET_QUOTATION_ITEMS_GROUP_BY_PARENT_SERVICE_TYPE_ERROR";
};
