export const ActionType = {
    //do request
    SERVICE_CREATE_REQUEST: "CREATE_SERVICE_REQUEST",
    SERVICE_CREATE_SUCCESS: "CREATE_SERVICE_SUCCESS",
    SERVICE_CREATE_ERROR: "CREATE_SERVICE_ERROR",

    SERVICE_EDIT_REQUEST: "EDIT_SERVICE_REQUEST",
    SERVICE_EDIT_SUCCESS: "EDIT_SERVICE_SUCCESS",
    SERVICE_EDIT_ERROR: "EDIT_SERVICE_ERROR",

    SERVICE_DELETE_REQUEST: "DELETE_SERVICE_REQUEST",
    SERVICE_DELETE_SUCCESS: "DELETE_SERVICE_SUCCESS",
    SERVICE_DELETE_ERROR: "DELETE_SERVICE_ERROR",


    //get request
    GET_SPECIFY_SERVICE_REQUEST: "GET_SPECIFY_SERVICE_REQUEST",
    GET_SPECIFY_SERVICE_SUCCESS: "GET_SPECIFY_SERVICE_SUCCESS",
    GET_SPECIFY_SERVICE_ERROR: "GET_SPECIFY_SERVICE_ERROR",

    GET_SERVICES_REQUEST: "GET_SERVICES_REQUEST",
    GET_SERVICES_SUCCESS: "GET_SERVICES_SUCCESS",
    GET_SERVICES_ERROR: "GET_SERVICES_ERROR",

    GET_ALL_SERVICES_REQUEST: "GET_ALL_SERVICES_REQUEST",
    GET_ALL_SERVICES_SUCCESS: "GET_ALL_SERVICES_SUCCESS",
    GET_ALL_SERVICES_ERROR: "GET_ALL_SERVICES_ERROR",

    LIST_SERVICES_WITH_PAGING_REQUEST: "LIST_SERVICES_WITH_PAGING_REQUEST",
    LIST_SERVICES_WITH_PAGING_SUCCESS: "LIST_SERVICES_WITH_PAGING_SUCCESS",
    LIST_SERVICES_WITH_PAGING_ERROR: "LIST_SERVICES_WITH_PAGING_ERROR"
};
