export module ActionType {
    //do request
    export const ACCESSARY_UNIT_CREATE_REQUEST = "CREATE_ACCESSARY_UNIT_REQUEST";
    export const ACCESSARY_UNIT_CREATE_SUCCESS = "CREATE_ACCESSARY_UNIT_SUCCESS";
    export const ACCESSARY_UNIT_CREATE_ERROR = "CREATE_ACCESSARY_UNIT_ERROR";

    export const ACCESSARY_UNIT_EDIT_REQUEST = "EDIT_ACCESSARY_UNIT_REQUEST";
    export const ACCESSARY_UNIT_EDIT_SUCCESS = "EDIT_ACCESSARY_UNIT_SUCCESS";
    export const ACCESSARY_UNIT_EDIT_ERROR = "EDIT_ACCESSARY_UNIT_ERROR";

    export const ACCESSARY_UNIT_DELETE_REQUEST = "DELETE_ACCESSARY_UNIT_REQUEST";
    export const ACCESSARY_UNIT_DELETE_SUCCESS = "DELETE_ACCESSARY_UNIT_SUCCESS";
    export const ACCESSARY_UNIT_DELETE_ERROR = "DELETE_ACCESSARY_UNIT_ERROR";

    //get request
    export const GET_UNIQUE_ACCESSARY_UNIT_REQUEST = "GET_UNIQUE_ACCESSARY_UNIT_REQUEST";
    export const GET_UNIQUE_ACCESSARY_UNIT_SUCCESS = "GET_UNIQUE_ACCESSARY_UNIT_SUCCESS";
    export const GET_UNIQUE_ACCESSARY_UNIT_ERROR = "GET_UNIQUE_ACCESSARY_UNIT_ERROR";

    export const GET_ACCESSARY_UNITS_REQUEST = "GET_ACCESSARY_UNITS_REQUEST";
    export const GET_ACCESSARY_UNITS_SUCCESS = "GET_ACCESSARY_UNITS_SUCCESS";
    export const GET_ACCESSARY_UNITS_ERROR = "GET_ACCESSARY_UNITS_ERROR";

    export const LIST_ACCESSARY_UNITS_WITH_PAGING_REQUEST = "LIST_ACCESSARY_UNITS_WITH_PAGING_REQUEST";
    export const LIST_ACCESSARY_UNITS_WITH_PAGING_SUCCESS = "LIST_ACCESSARY_UNITS_WITH_PAGING_SUCCESS";
    export const LIST_ACCESSARY_UNITS_WITH_PAGING_ERROR = "LIST_ACCESSARY_UNITS_WITH_PAGING_ERROR";
}
