export module ActionType {
    //do request
    export const CUSTOMER_TYPE_CREATE_REQUEST = "CREATE_CUSTOMER_TYPE_REQUEST";
    export const CUSTOMER_TYPE_CREATE_SUCCESS = "CREATE_CUSTOMER_TYPE_SUCCESS";
    export const CUSTOMER_TYPE_CREATE_ERROR = "CREATE_CUSTOMER_TYPE_ERROR";

    export const CUSTOMER_TYPE_EDIT_REQUEST = "EDIT_CUSTOMER_TYPE_REQUEST";
    export const CUSTOMER_TYPE_EDIT_SUCCESS = "EDIT_CUSTOMER_TYPE_SUCCESS";
    export const CUSTOMER_TYPE_EDIT_ERROR = "EDIT_CUSTOMER_TYPE_ERROR";

    export const CUSTOMER_TYPE_DELETE_REQUEST = "DELETE_CUSTOMER_TYPE_REQUEST";
    export const CUSTOMER_TYPE_DELETE_SUCCESS = "DELETE_CUSTOMER_TYPE_SUCCESS";
    export const CUSTOMER_TYPE_DELETE_ERROR = "DELETE_CUSTOMER_TYPE_ERROR";

    //get request
    export const GET_UNIQUE_CUSTOMER_TYPE_REQUEST = "GET_UNIQUE_CUSTOMER_TYPE_REQUEST";
    export const GET_UNIQUE_CUSTOMER_TYPE_SUCCESS = "GET_UNIQUE_CUSTOMER_TYPE_SUCCESS";
    export const GET_UNIQUE_CUSTOMER_TYPE_ERROR = "GET_UNIQUE_CUSTOMER_TYPE_ERROR";

    export const GET_CUSTOMERS_TYPE_REQUEST = "GET_CUSTOMERS_TYPE_REQUEST";
    export const GET_CUSTOMERS_TYPE_SUCCESS = "GET_CUSTOMERS_TYPE_SUCCESS";
    export const GET_CUSTOMERS_TYPE_ERROR = "GET_CUSTOMERS_TYPE_ERROR";

    export const LIST_CUSTOMERS_TYPE_WITH_PAGING_REQUEST = "LIST_CUSTOMERS_TYPE_WITH_PAGING_REQUEST";
    export const LIST_CUSTOMERS_TYPE_WITH_PAGING_SUCCESS = "LIST_CUSTOMERS_TYPE_WITH_PAGING_SUCCESS";
    export const LIST_CUSTOMERS_TYPE_WITH_PAGING_ERROR = "LIST_CUSTOMERS_TYPE_WITH_PAGING_ERROR";
}
