export module ActionType {
    //do request
    export const SERVICE_TYPE_CREATE_REQUEST = "CREATE_SERVICE_TYPE_REQUEST";
    export const SERVICE_TYPE_CREATE_SUCCESS = "CREATE_SERVICE_TYPE_SUCCESS";
    export const SERVICE_TYPE_CREATE_ERROR = "CREATE_SERVICE_TYPE_ERROR";

    export const SERVICE_TYPE_EDIT_REQUEST = "EDIT_SERVICE_TYPE_REQUEST";
    export const SERVICE_TYPE_EDIT_SUCCESS = "EDIT_SERVICE_TYPE_SUCCESS";
    export const SERVICE_TYPE_EDIT_ERROR = "EDIT_SERVICE_TYPE_ERROR";

    export const SERVICE_TYPE_DELETE_REQUEST = "DELETE_SERVICE_TYPE_REQUEST";
    export const SERVICE_TYPE_DELETE_SUCCESS = "DELETE_SERVICE_TYPE_SUCCESS";
    export const SERVICE_TYPE_DELETE_ERROR = "DELETE_SERVICE_TYPE_ERROR";

    //get request
    export const GET_UNIQUE_SERVICE_TYPE_REQUEST = "GET_UNIQUE_SERVICE_TYPE_REQUEST";
    export const GET_UNIQUE_SERVICE_TYPE_SUCCESS = "GET_UNIQUE_SERVICE_TYPE_SUCCESS";
    export const GET_UNIQUE_SERVICE_TYPE_ERROR = "GET_UNIQUE_SERVICE_TYPE_ERROR";

    export const GET_SERVICE_TYPES_REQUEST = "GET_SERVICE_TYPES_REQUEST";
    export const GET_SERVICE_TYPES_SUCCESS = "GET_SERVICE_TYPES_SUCCESS";
    export const GET_SERVICE_TYPES_ERROR = "GET_SERVICE_TYPES_ERROR";

    export const LIST_SERVICE_TYPES_WITH_PAGING_REQUEST = "LIST_SERVICE_TYPES_WITH_PAGING_REQUEST";
    export const LIST_SERVICE_TYPES_WITH_PAGING_SUCCESS = "LIST_SERVICE_TYPES_WITH_PAGING_SUCCESS";
    export const LIST_SERVICE_TYPES_WITH_PAGING_ERROR = "LIST_SERVICE_TYPES_WITH_PAGING_ERROR";
    
    export const GET_PARENT_SERVICE_TYPES_REQUEST = "GET_PARENT_SERVICE_TYPES_REQUEST";
    export const GET_PARENT_SERVICE_TYPES_SUCCESS = "GET_PARENT_SERVICE_TYPES_SUCCESS";
    export const GET_PARENT_SERVICE_TYPES_ERROR = "GET_PARENT_SERVICE_TYPES_ERROR";
}
