export module ActionType {
    //do request
    export const CAR_MODEL_CREATE_REQUEST = "CREATE_CAR_MODEL_REQUEST";
    export const CAR_MODEL_CREATE_SUCCESS = "CREATE_CAR_MODEL_SUCCESS";
    export const CAR_MODEL_CREATE_ERROR = "CREATE_CAR_MODEL_ERROR";

    export const CAR_MODEL_EDIT_REQUEST = "EDIT_CAR_MODEL_REQUEST";
    export const CAR_MODEL_EDIT_SUCCESS = "EDIT_CAR_MODEL_SUCCESS";
    export const CAR_MODEL_EDIT_ERROR = "EDIT_CAR_MODEL_ERROR";

    export const CAR_MODEL_DELETE_REQUEST = "DELETE_CAR_MODEL_REQUEST";
    export const CAR_MODEL_DELETE_SUCCESS = "DELETE_CAR_MODEL_SUCCESS";
    export const CAR_MODEL_DELETE_ERROR = "DELETE_CAR_MODEL_ERROR";

    //get request
    export const GET_UNIQUE_CAR_MODEL_REQUEST = "GET_UNIQUE_CAR_MODEL_REQUEST";
    export const GET_UNIQUE_CAR_MODEL_SUCCESS = "GET_UNIQUE_CAR_MODEL_SUCCESS";
    export const GET_UNIQUE_CAR_MODEL_ERROR = "GET_UNIQUE_CAR_MODEL_ERROR";

    export const GET_CAR_MODELS_REQUEST = "GET_CAR_MODELS_REQUEST";
    export const GET_CAR_MODELS_SUCCESS = "GET_CAR_MODELS_SUCCESS";
    export const GET_CAR_MODELS_ERROR = "GET_CAR_MODELS_ERROR";

    export const GET_ALL_CAR_MODELS_REQUEST = "GET_ALL_CAR_MODELS_REQUEST";
    export const GET_ALL_CAR_MODELS_SUCCESS = "GET_ALL_CAR_MODELS_SUCCESS";
    export const GET_ALL_CAR_MODELS_ERROR = "GET_ALL_CAR_MODELS_ERROR";

    export const LIST_CAR_MODELS_WITH_PAGING_REQUEST = "LIST_CAR_MODELS_WITH_PAGING_REQUEST";
    export const LIST_CAR_MODELS_WITH_PAGING_SUCCESS = "LIST_CAR_MODELS_WITH_PAGING_SUCCESS";
    export const LIST_CAR_MODELS_WITH_PAGING_ERROR = "LIST_CAR_MODELS_WITH_PAGING_ERROR"
}
