export module ActionType {
    //do request
    export const GARAGE_UPDATE_REQUEST = "GARAGE_UPDATE_REQUEST";
    export const GARAGE_UPDATE_SUCCESS = "GARAGE_UPDATE_SUCCESS";
    export const GARAGE_UPDATE_ERROR = "GARAGE_UPDATE_ERROR";

    //get request
    export const GET_GARAGE_INFORMATION_REQUEST = "GET_GARAGE_INFORMATION_REQUEST";
    export const  GET_GARAGE_INFORMATION_SUCCESS = "GET_GARAGE_INFORMATION_SUCCESS";
    export const GET_GARAGE_INFORMATION_ERROR = "GET_GARAGE_INFORMATION_ERROR";
}
