export module ActionType {
    //do request
    export const CAR_CREATE_REQUEST = "CAR_CREATE_REQUEST";
    export const CAR_CREATE_SUCCESS = "CAR_CREATE_SUCCESS";
    export const CAR_CREATE_ERROR = "CAR_CREATE_ERROR";

    export const CAR_EDIT_REQUEST = "CAR_EDIT_REQUEST";
    export const CAR_EDIT_SUCCESS = "CAR_EDIT_SUCCESS";
    export const CAR_EDIT_ERROR = "CAR_EDIT_ERROR";

    export const CAR_DELETE_REQUEST = "DELETE_CAR_REQUEST";
    export const CAR_DELETE_SUCCESS = "DELETE_CAR_SUCCESS";
    export const CAR_DELETE_ERROR = "DELETE_CAR_ERROR";

    //get request
    export const GET_UNIQUE_CAR_REQUEST = "GET_UNIQUE_CAR_REQUEST";
    export const GET_UNIQUE_CAR_SUCCESS = "GET_UNIQUE_CAR_SUCCESS";
    export const GET_UNIQUE_CAR_ERROR = "GET_UNIQUE_CAR_ERROR";

    export const GET_CAR_BY_CUSTOMER_REQUEST = "GET_CAR_BY_CUSTOMER_REQUEST";
    export const GET_CAR_BY_CUSTOMER_SUCCESS = "GET_CAR_BY_CUSTOMER_SUCCESS";
    export const GET_CAR_BY_CUSTOMER_ERROR = "GET_CAR_BY_CUSTOMER_ERROR";

    export const GET_CARS_REQUEST = "GET_CARS_REQUEST";
    export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
    export const GET_CARS_ERROR = "GET_CARS_ERROR";

    export const GET_OWNED_CARS_REQUEST = "GET_OWNED_CARS_REQUEST";
    export const GET_OWNED_CARS_SUCCESS = "GET_OWNED_CARS_SUCCESS";
    export const GET_OWNED_CARS_ERROR = "GET_OWNED_CARS_ERROR";

    export const LIST_CARS_WITH_PAGING_REQUEST = "LIST_CARS_WITH_PAGING_REQUEST";
    export const LIST_CARS_WITH_PAGING_SUCCESS = "LIST_CARS_WITH_PAGING_SUCCESS";
    export const LIST_CARS_WITH_PAGING_ERROR = "LIST_CARS_WITH_PAGING_ERROR";

    //temporary
    export const GET_ALL_MANUFACTURERS_REQUEST = "GET_ALL_MANUFACTURERS_REQUEST";
    export const GET_ALL_MANUFACTURERS_SUCCESS = "GET_ALL_MANUFACTURERS_SUCCESS";
    export const GET_ALL_MANUFACTURERS_ERROR = "GET_ALL_MANUFACTURERS_ERROR";

    export const GET_MODELS_BY_MANUFACTURER_REQUEST = "GET_MODELS_BY_MANUFACTURER_REQUEST";
    export const GET_MODELS_BY_MANUFACTURER_SUCCESS = "GET_MODELS_BY_MANUFACTURER_SUCCESS";
    export const GET_MODELS_BY_MANUFACTURER_ERROR = "GET_MODELS_BY_MANUFACTURER_ERROR";

    export const GET_YEARS_BY_MODEL_REQUEST = "GET_YEARS_BY_MODEL_REQUEST";
    export const GET_YEARS_BY_MODEL_SUCCESS = "GET_YEARS_BY_MODEL_SUCCESS";
    export const GET_YEARS_BY_MODEL_ERROR = "GET_YEARS_BY_MODEL_ERROR";
}
