export module ActionType {
    //do request
    export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
    export const CATEGORY_CREATE_SUCCESS = "CREATE_CATEGORY_SUCCESS";
    export const CATEGORY_CREATE_ERROR = "CREATE_CATEGORY_ERROR";

    export const CATEGORY_EDIT_REQUEST = "EDIT_CATEGORY_REQUEST";
    export const CATEGORY_EDIT_SUCCESS = "EDIT_CATEGORY_SUCCESS";
    export const CATEGORY_EDIT_ERROR = "EDIT_CATEGORY_ERROR";

    export const CATEGORY_DELETE_REQUEST = "DELETE_CATEGORY_REQUEST";
    export const CATEGORY_DELETE_SUCCESS = "DELETE_CATEGORY_SUCCESS";
    export const CATEGORY_DELETE_ERROR = "DELETE_CATEGORY_ERROR";

    //get request
    export const GET_SPECIFIC_CATEGORY_REQUEST = "GET_SPECIFIC_CATEGORY_REQUEST";
    export const GET_SPECIFIC_CATEGORY_SUCCESS = "GET_SPECIFIC_CATEGORY_SUCCESS";
    export const GET_SPECIFIC_CATEGORY_ERROR = "GET_SPECIFIC_CATEGORY_ERROR";

    export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
    export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
    export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

    export const LIST_CATEGORIES_WITH_PAGING_REQUEST = "LIST_CATEGORIES_WITH_PAGING_REQUEST";
    export const LIST_CATEGORIES_WITH_PAGING_SUCCESS = "LIST_CATEGORIES_WITH_PAGING_SUCCESS";
    export const LIST_CATEGORIES_WITH_PAGING_ERROR = "LIST_CATEGORIES_WITH_PAGING_ERROR";

    export const GET_PARENT_CATEGORIES_REQUEST = "GET_PARENT_CATEGORIES_REQUEST";
    export const GET_PARENT_CATEGORIES_SUCCESS = "GET_PARENT_CATEGORIES_SUCCESS";
    export const GET_PARENT_CATEGORIES_ERROR = "GET_PARENT_CATEGORIES_ERROR";
}
